# Generated by Django 4.1.5 on 2023-01-12 15:56

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DWH', '0002_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_to_notice',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='user',
            name='time_to_notificate',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
