# Generated by Django 4.1.5 on 2023-01-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DWH', '0003_user_time_to_notice_user_time_to_notificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='time_to_notice',
        ),
        migrations.RemoveField(
            model_name='user',
            name='time_to_notificate',
        ),
    ]
