# Generated by Django 4.1.5 on 2023-01-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DWH', '0004_remove_user_time_to_notice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
