# Generated by Django 4.1.5 on 2023-01-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DWH', '0005_user_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
