# Generated by Django 4.1.5 on 2023-01-14 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DWH', '0007_user_city_alter_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_to_notificate',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
