# Generated by Django 4.1.5 on 2023-01-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DWH', '0008_user_time_to_notificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_to_notificate',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
